### ISSUE TITLE
Allow adding labels without highlighting emote

### ISSUE THREAD

**Issue by Zoboomaku** [equirs/emotes#5]
I find the labels to be easier than the in-game icons for identifying the emote I'm searching for, but don't care to have every emote highlighted.

**Comment by equirs** [comment]
This is more or less already possible by setting your highlight colors to max alpha (i.e., transparent), isn't it? Maybe it's a bit annoying from a user perspective to have to highlight things first if you're only wanting labels. Could look into separating the two

**Comment by Zoboomaku** [comment]
No, you're absolutely right, and that's a solution I've used in other plugins to achieve similar results in those, so I'm surprised it didn't occur to me.  Thanks
